# Generated by Django 4.0.1 on 2022-05-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_staff', models.IntegerField()),
            ],
            options={
                'db_table': 'college',
            },
        ),
    ]
