# Generated by Django 4.0.1 on 2022-05-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_rest', '0002_college'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='is_staff',
            new_name='staff_count',
        ),
    ]
