# Generated by Django 4.0.1 on 2022-05-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_rest', '0003_rename_is_staff_college_staff_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.SmallIntegerField(default=0),
        ),
    ]
